# Generated by Django 6.0 on 2025-12-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='tag',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('billing', 'Billing Issues'), ('tech', 'Technical Support'), ('complaint', 'Complaint')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
